apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: ahmedrira/student-management:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root123
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
---
apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: devops
spec:
  selector:
    app: student-management
  type: NodePort
  ports:
    - port: 8080        # port dans le cluster
      targetPort: 8080  # port dans le conteneur
      nodePort: 30080   # port du node
